# echo "(v${VERSION}) ${MSG}" > {{.COMMIT_MSG_FILE}}
# echo {0} {1} {2} {3}

pre-commit:
  commands:
    tag:
      run: echo "pre-commit" && devbox run -- task lefthook:pre-commit
post-commit:
  commands:
    tag:
      run: echo "post-commit" && devbox run -- task lefthook:post-commit
      skip:
        - run: |
            MSG="$(git log -1 --pretty=format:%s)"
            echo "$MSG" | grep -q "^(v" && exit 0 || exit 1
