name: bno-lang-rust
version: ""
description: Setup runtime Rust
readme: README.md
include: []
create_files: {}

env:
  RUST_VERSION: 1.77.2

packages:
  libiconv:
    version: latest
  rustup:
    version: latest

shell:
  scripts: {}
  init_hook:
    - |
      export RUSTUP_HOME="$REPO_ROOT/.devbox/runtimes/rust"
      export LIBRARY_PATH="$LIBRARY_PATH:"$REPO_ROOT/.devbox/nix/profile/default/lib"
      mkdir -p "$RUSTUP_HOME"
      rustup default "$RUST_VERSION"
      # rustup default stable
      cargo fetch &>/dev/null
