name: bno-lang-rust
version: ""
description: Setup runtime Rust
readme: README.md
include: []
create_files: {}

env:
  RUSTUP_HOME: "$PWD/.devbox/runtimes/rust"
  LIBRARY_PATH: "$LIBRARY_PATH:$PWD/.devbox/nix/profile/default/lib"

packages:
  libiconv:
    version: latest
  rustup:
    version: latest

shell:
  scripts: {}
  init_hook:
    - |
      function __log_echo() {
        if [[ "${REPO_SCRIPT_DEBUG-1}" == "1" ]]; then
          echo "$1"
        fi
      }
      
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      __log_echo "  Initializing Devbox: Rust"
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      
      __log_echo " ➜ RUSTUP_HOME: $RUSTUP_HOME"
      __log_echo " ➜ LIBRARY_PATH: $LIBRARY_PATH"
      
      __log_echo " ➜ Create home directory"
      mkdir -p "$RUSTUP_HOME"
      
      __log_echo " ➜ Install rust toolchain"
      
      __log_echo "$(rustup toolchain install nightly)"
      __log_echo "$(rustup default stable)"
      __log_echo "$(rustup component add clippy)"
      __log_echo "$(rustup component add rust-src)"
      
      __log_echo " ➜ Run cargo fetch"
      cargo fetch &>/dev/null
      
      __log_echo " ➜ Details"
      __log_echo "$(rustup show)"


# RUST_VERSION: 1.77.2
# rustup default "$RUST_VERSION" 1>/dev/null # stable
# __log_echo " ➜ RUST_VERSION: $RUST_VERSION"
# log_step_sub "Load completions"
# source "$REPO_ROOT/.devbox/nix/profile/default/share/bash-completion/completions/cargo"