name: bno-lang-rust
version: ""
description: Setup runtime Rust
readme: README.md
include: []
create_files: {}

env:
  RUST_VERSION: 1.77.2

packages:
  libiconv:
    version: latest
  rustup:
    version: latest

shell:
  scripts: {}
  init_hook:
    - |
      echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      echo "  Initializing Devbox: Rust"
      echo "   ➜ RUST_VERSION: $RUST_VERSION"
      echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      
      export RUSTUP_HOME="$REPO_ROOT/.devbox/runtimes/rust"
      export LIBRARY_PATH="$LIBRARY_PATH:$REPO_ROOT/.devbox/nix/profile/default/lib"
      mkdir -p "$RUSTUP_HOME"
      
      echo " ➜ Install rust toolchain"
      rustup default "$RUST_VERSION" # stable
      
      echo " ➜ Run cargo fetch"
      cargo fetch &>/dev/null
      
      # log_step_sub "Load completions"
      # source "$REPO_ROOT/.devbox/nix/profile/default/share/bash-completion/completions/cargo"
