$schema: https://raw.githubusercontent.com/jetpack-io/devbox/0.13.4/.schema/devbox.schema.json
name: bno-lang-go
version: ""
description: Setup runtime GO
readme: README.md

env:
  GO_VERSION: 1.23.1
  GOPATH: $PWD/.devbox/runtimes/go
  PATH: $PWD/.devbox/runtimes/go/bin:$PATH

packages:
  go: "1.23.1"
  golangci-lint: "1.61.0"

shell:
  init_hook:
    - |
      function __log_echo() {
        if [[ "${REPO_SCRIPT_DEBUG-1}" == "1" ]]; then
          echo "$1"
        fi
      }
      
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      __log_echo "  Initializing Devbox: Go"
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      
      __log_echo " ➜ GOPATH: $GOPATH"
      __log_echo " ➜ GO_VERSION: $(go version)"
      
      __log_echo " ➜ Create GOPATH directory"
      mkdir -p "$GOPATH"
      mkdir -p "$GOPATH/bin"

