name: bno-lang-go
version:
  name: '@booknorder/config-env'
  version: 0.1.0
  scripts: {}
  devDependencies:
    lefthook: 1.6.10
description: Setup runtime GO
readme: README.md
include: []
create_files: {}
env:
  GO_VERSION: 1.20.2
packages:
  go:
    version: 1.20.2
  golangci-lint:
    version: '1.52'
shell:
  scripts: {}
  init_hook: []
