name: bno-lang-node
version: ""
description: Setup runtime Node.js
readme: README.md
include: []
create_files: {}

env:
  DENO_VERSION: 1.43.5
  NODE_VERSION: 20.11.1
  PNPM_VERSION: 8.15.5

packages:
  deno:
    version: 1.43.5
  nodejs:
    version: 20.11.1
  nodePackages.pnpm:
    version: 8.15.5

shell:
  scripts: {}
  init_hook:
    - |
      function __log_echo() {
        if [[ "${REPO_SCRIPT_DEBUG-1}" == "1" ]]; then
          echo "$1"
        fi
      }
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      __log_echo "  Initializing Devbox: Node.js"
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      
      
      __log_echo " ➜ NODE_VERSION: $(node -v)"
      __log_echo " ➜ PNPM_VERSION: $(pnpm -v)"
      __log_echo " ➜ DENO_VERSION: $(deno --version)"

