$schema: https://raw.githubusercontent.com/jetpack-io/devbox/0.16.0/.schema/devbox-plugin.schema.json
name: bno-lang-node
version: ""
description: Setup runtime Nodejs
readme: README.md

env:
  DENO_VERSION: "1.46.3"
  NODE_VERSION: "22.14.0"
  DEVBOX_COREPACK_ENABLED: "true"

packages:
  deno: "1.46.3"
  nodejs: "22.14.0"

shell:
  init_hook:
    - |
      function __log_echo() {
        if [[ "${REPO_SCRIPT_DEBUG-1}" == "1" ]]; then
          echo "$1"
        fi
      }
      
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      __log_echo "  Initializing Devbox: Node.js"
      __log_echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      __log_echo " ➜ NODE_VERSION: $(node -v)"
      __log_echo " ➜ DENO_VERSION: $(deno --version)"

