name: tag-release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: ["main"]
    tags: ["**"]

env: {}
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create Release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TAG: ${{ github.ref_name }}
          MSG: ${{ github.event.head_commit.message }}
        run: |
          gh release create "$TAG" \
            --repo "$OWNER/$REPO" \
            --title "$TAG" \
            --notes "$MSG"
